name: Update VPN Servers

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Fetch VPN servers
        run: |
          python -c '
          import requests
          import json
          from datetime import datetime
          
          response = requests.get("http://www.vpngate.net/api/iphone/")
          
          with open("vpn_servers.json", "w") as f:
              json.dump({
                  "last_updated": datetime.now().isoformat(),
                  "data": response.text
              }, f)
          '
          
      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add vpn_servers.json
          git commit -m "Update VPN servers" || exit 0
          git push
