name: Update VPN Servers Gist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: b3049dbc387bf59cbf6810ae0ee90aff
        run: |
          python -c '
          import requests
          import json
          import os
          import sys
          from datetime import datetime
          
          try:
              # Fetch VPN servers with detailed error handling
              print("Fetching VPN servers...")
              vpn_response = requests.get(
                  "http://www.vpngate.net/api/iphone/",
                  headers={"User-Agent": "Mozilla/5.0"},
                  timeout=10
              )
              vpn_response.raise_for_status()
              print("VPN servers fetched successfully")
              
              # Prepare Gist update
              print("Preparing Gist update...")
              headers = {
                  "Authorization": f"Bearer {os.environ[\"GIST_TOKEN\"]}",
                  "Accept": "application/vnd.github.v3+json"
              }
              
              content = {
                  "last_updated": datetime.now().isoformat(),
                  "data": vpn_response.text
              }
              
              gist_data = {
                  "files": {
                      "vpn_servers.json": {
                          "content": json.dumps(content, indent=2)
                      }
                  }
              }
              
              # Update Gist
              print("Updating Gist...")
              gist_response = requests.patch(
                  f"https://api.github.com/gists/{os.environ[\"GIST_ID\"]}",
                  headers=headers,
                  json=gist_data
              )
              
              if gist_response.status_code != 200:
                  print(f"Error response: {gist_response.text}")
                  sys.exit(1)
                  
              print("Gist updated successfully")
              
          except Exception as e:
              print(f"Error: {str(e)}")
              sys.exit(1)
          '
