name: Update VPN Servers

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-servers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Fetch VPN servers
        run: |
          python <<EOF
          import requests
          import json
          from datetime import datetime
          
          try:
              headers = {
                  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
              }
              print("Fetching VPN servers...")
              response = requests.get('http://www.vpngate.net/api/iphone/', headers=headers)
              
              if response.status_code == 200:
                  print("Successfully fetched data")
                  with open('vpn_servers.json', 'w') as f:
                      json.dump({
                          'last_updated': datetime.now().isoformat(),
                          'data': response.text
                      }, f, indent=2)
                  print("Data saved to vpn_servers.json")
              else:
                  print(f"Failed to fetch data: {response.status_code}")
                  
          except Exception as e:
              print(f"Error: {str(e)}")
              exit(1)
          EOF
          
      - name: Commit and push if changed
        run: |
          if [[ -f vpn_servers.json ]]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add vpn_servers.json
            git diff --quiet && git diff --staged --quiet || git commit -m "Update VPN servers $(date -u)"
            git push
            echo "Successfully updated vpn_servers.json"
          else
            echo "vpn_servers.json not found!"
            exit 1
          fi
