name: Update VPN Servers

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Fetch VPN servers
        run: |
          python <<EOF
          import requests
          import json
          from datetime import datetime
          
          try:
              headers = {
                  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
              }
              response = requests.get('http://www.vpngate.net/api/iphone/', headers=headers)
              response.raise_for_status()
              
              with open('vpn_servers.json', 'w') as f:
                  json.dump({
                      'last_updated': datetime.now().isoformat(),
                      'data': response.text
                  }, f, indent=2)
          except Exception as e:
              print(f"Error: {str(e)}")
              exit(1)
          EOF
          
      - name: Configure Git
        run: |
          git config --global user.name "Morteza Bahmani"
          git config --global user.email "morteza.bahmani@gmail.com"
          
      - name: Commit and push
        run: |
          git add vpn_servers.json
          git commit -m "Update VPN servers" || echo "No changes"
          git push || (git pull --rebase && git push)
