name: Update VPN Servers

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Fetch and save VPN servers
        run: |
          python <<EOF
          import requests
          import json
          from datetime import datetime
          
          headers = {'User-Agent': 'Mozilla/5.0'}
          response = requests.get('http://www.vpngate.net/api/iphone/', headers=headers)
          
          with open('vpn_servers.json', 'w') as f:
              json.dump({
                  'last_updated': datetime.now().isoformat(),
                  'data': response.text
              }, f)
          EOF
          
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git remote set-url origin git@github.com:mortezabahmani/vpngate-mirror.git
          git add vpn_servers.json
          git commit -m "Update VPN servers" || true
          git push
